# Generated by Django 5.0 on 2024-02-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(default='Blog', max_length=100),
            preserve_default=False,
        ),
    ]
